### ISSUE TITLE
OnlyKey

### ISSUE THREAD

**Issue by openbrian** [hillbrad/U2FReviews#3]
Can you review OnlyKey. https://crp.to/

**Comment by hillbrad** [comment]
An interesting but kind of weird device. Like the 1st generation U2F Zero, it seems to miss the point of U2F that you can use one device for an unlimited number of logins.  (limit of 12 logins, and U2F only supported on the US version)  It also misses the point of simplicity.  It's more like a spy toy than something usable by regular people. U2F Zero was fun to play with for $8, but I don't think I want to spend $50 for one of these.

**Comment by Mycrypto** [comment]
@hillbrad A few things to clear up here

U2F is supported on the standard edition that ships to US and Europe. You can also load the standard edition on any OnlyKey that ships globally.

You can use U2F for an unlimited number of sites. The limit of 12 is for storage of URLs, Usernames, Passwords.
