### ISSUE TITLE
Some Android devices don't have NFC, thus need a Bluetooth security key.

### ISSUE THREAD

**Issue by dconnolly** [hillbrad/U2FReviews#6]
For example, the Pixel C. It would be nice if the Yubikey 4C's worked on the devices that have USB-C ports, like the Pixel C, but as of now, they don't work. For these types of devices the only option is a Bluetooth security key.

**Comment by onlykey** [comment]
OnlyKey is working on an Android app that supports U2F over USB as many Android devices don't support NFC

**Comment by hillbrad** [comment]
https://github.com/hillbrad/U2FReviews/commit/7a1eb880056a376ebb02534184c24321b746ad66
